Repository DeveloperAcademy-POSTECH/2025-C4-M7-TPAP, pull requests merged in 2025-07, with the labels that each got.

#108 #57 초대 코드 생성 및 참여 기능 구현
  Projects/Rootrip/Rootrip/DebuggingViews/InviteView.swift
  Projects/Rootrip/Rootrip/Models/ModelStructures/Project.swift
  Projects/Rootrip/Rootrip/Models/ModelStructures/ProjectInvitation .swift
  Projects/Rootrip/Rootrip/Models/ProjectInvitationProtocol.swift
  Projects/Rootrip/Rootrip/Models/Repositories/ProjectInvitationRepository.swift
  Projects/Rootrip/Rootrip/ViewModels/InviteViewModel.swift
Labels: Feature

#117 refactoring, 파이어 베이스 연결을 위한 데이터 타입 수정 & 파일 구조 수정
  Projects/Rootrip/Rootrip/Models/ModelStructures/StrokeData.swift
  Projects/Rootrip/Rootrip/Models/ModelStructures/StrokePointData.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/BookmarkRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/MapDetailRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/PlanRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/ProjectRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/StrokeDataRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/StrokePointDataRepositoryProtocol.swift
Labels: Refactoring

#118 Feat/61 design component
  Projects/Rootrip/Rootrip.xcodeproj/project.pbxproj
  Projects/Rootrip/Rootrip/Info.plist
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/accent1.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/accent2.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/accent3.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/mainbackground.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/maintext.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/primary1.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/primary2.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/secondary1.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/secondary2.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/secondary3.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Colors.xcassets/secondary4.colorset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Font/FontResource.swift
  Projects/Rootrip/Rootrip/Resources/Font/Pretendard-Bold.otf
  Projects/Rootrip/Rootrip/Resources/Font/Pretendard-Medium.otf
  Projects/Rootrip/Rootrip/Resources/Font/Pretendard-Regular.otf
  Projects/Rootrip/Rootrip/Resources/Font/Pretendard-SemiBold.otf
  Projects/Rootrip/Rootrip/Views/Componants/MainViewToolBar.swift
  Projects/Rootrip/Rootrip/Views/Componants/MapCanvasToolBar.swift
  Projects/Rootrip/Rootrip/Views/Componants/ProjectCard.swift
  Projects/Rootrip/Rootrip/Views/Componants/SectionButtomLable.swift
  Projects/Rootrip/Rootrip/Views/ContentView.swift
  Projects/Rootrip/Rootrip/Views/Map/ProjectView.swift
  Projects/Rootrip/Rootrip/Views/Map/TimeAnnotation.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Plan/PlaceListView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Plan/PlanButton.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/SegmentedContolView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SidebarToggleView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SidebarView.swift
Labels: Feature

#121 #120 섹션버튼 로직 추가
  Projects/Rootrip/Rootrip/ViewModels/PlanManager.swift
Labels: BugFix

#126 Feat/26 login view UI
  Projects/Rootrip/Rootrip/App/RootripApp.swift
  Projects/Rootrip/Rootrip/Info.plist
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/applebutton.imageset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/applebutton.imageset/applebutton.svg
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/loginbackground.imageset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/loginbackground.imageset/loginbackground.svg
  Projects/Rootrip/Rootrip/Resources/Font/DarumadropOne-Regular.ttf
  Projects/Rootrip/Rootrip/Resources/Font/FontResource.swift
  Projects/Rootrip/Rootrip/Views/ContentView.swift
  Projects/Rootrip/Rootrip/Views/LoginView.swift
Labels: Feature

#128 Feat/113 utilpen
  Projects/Rootrip/Rootrip/ViewModels/CanvasViewController.swift
  Projects/Rootrip/Rootrip/ViewModels/PLACEHOLDER3.swift
  Projects/Rootrip/Rootrip/ViewModels/UtilPen.swift
  Projects/Rootrip/Rootrip/ViewModels/UtilPenDelegate.swift
  Projects/Rootrip/Rootrip/Views/Canvas/CanvasView.swift
  Projects/Rootrip/Rootrip/Views/Canvas/MapCanvasView.swift
  Projects/Rootrip/Rootrip/Views/Map/MapView.swift
Labels: Feature

#130 Feat/113 utilpen
  Projects/Rootrip/Rootrip/ViewModels/CanvasViewController.swift
  Projects/Rootrip/Rootrip/ViewModels/UtilPen.swift
  Projects/Rootrip/Rootrip/ViewModels/UtilPenDelegate.swift
  Projects/Rootrip/Rootrip/Views/Canvas/CanvasView.swift
  Projects/Rootrip/Rootrip/Views/Canvas/MapCanvasView.swift
  Projects/Rootrip/Rootrip/Views/Map/MapView.swift
Labels: Refactoring

#133 #125 프로젝트 생성/삭제 및 초대 코드 로직 구현
  Projects/Rootrip/Rootrip/DebuggingViews/InviteView.swift
  Projects/Rootrip/Rootrip/DebuggingViews/ProjectDetailView.swift
  Projects/Rootrip/Rootrip/DebuggingViews/RepositoryProtocolTestView.swift
  Projects/Rootrip/Rootrip/Models/ModelStructures/Project.swift
  Projects/Rootrip/Rootrip/Models/ModelStructures/ProjectInvitation .swift
  Projects/Rootrip/Rootrip/Models/Repositories/ProjectInvitationRepository.swift
  Projects/Rootrip/Rootrip/Models/Repositories/ProjectRepository.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/ProjectInvitationProtocol.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/ProjectRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/Resources/Font/FontResource.swift
  Projects/Rootrip/Rootrip/ViewModels/BlockViewModel.swift
  Projects/Rootrip/Rootrip/ViewModels/InviteViewModel.swift
  Projects/Rootrip/Rootrip/Views/BlockView.swift
  Projects/Rootrip/Rootrip/Views/Componants/DeleteAccountAlert.swift
  Projects/Rootrip/Rootrip/Views/Componants/InviteCodeInputView.swift
  Projects/Rootrip/Rootrip/Views/Componants/LogoutAlert.swift
  Projects/Rootrip/Rootrip/Views/Componants/MainViewToolBar.swift
  Projects/Rootrip/Rootrip/Views/Componants/MapCanvasToolBar.swift
  Projects/Rootrip/Rootrip/Views/Componants/PenThicknessSlider.swift
  Projects/Rootrip/Rootrip/Views/Componants/ProjectCard.swift
  Projects/Rootrip/Rootrip/Views/LoginView.swift
  Projects/Rootrip/Rootrip/Views/MainView.swift
  Projects/Rootrip/Rootrip/Views/ProjectListView.swift
Labels: Feature

#138 #26 로그인뷰 수정 및 앱아이콘 적용
  Projects/Rootrip/Rootrip/Info.plist
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/AppIcon.appiconset/rootripicon 1.jpg
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/AppIcon.appiconset/rootripicon 2.jpg
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/AppIcon.appiconset/rootripicon.jpg
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/R.imageset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/R.imageset/R.svg
  Projects/Rootrip/Rootrip/Resources/Font/FontResource.swift
  Projects/Rootrip/Rootrip/Resources/Font/SuezOne-Regular.ttf
  Projects/Rootrip/Rootrip/Views/LoginView.swift
Labels: Feature

#140 Feat/125 connect project data
  Projects/Rootrip/Rootrip/DebuggingViews/writeMapDetailView.swift
  Projects/Rootrip/Rootrip/Models/Repositories/MapDetailRepository.swift
  Projects/Rootrip/Rootrip/Models/RepositoryProtocols/MapDetailRepositoryProtocol.swift
  Projects/Rootrip/Rootrip/ViewModels/PlanManager.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Bookmark/BookmarkCard.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Bookmark/BookmarkView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Plan/PlanCard.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/Plan/PlanView.swift
Labels: Feature

#149 Feat/59 project view
  Projects/Rootrip/Rootrip/Views/Componants/searchBar.swift
  Projects/Rootrip/Rootrip/Views/LoginView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SegmentedControl/SegmentedContolView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SidebarToggleView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SidebarView.swift
Labels: Feature, Refactoring

#163 Fix/71 tool change
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/penOff.imageset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/penOff.imageset/penOff.png
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/penOn.imageset/Contents.json
  Projects/Rootrip/Rootrip/Resources/Assets.xcassets/penOn.imageset/penOn.png
  Projects/Rootrip/Rootrip/ViewModels/LocationManager.swift
  Projects/Rootrip/Rootrip/Views/Canvas/CanvasView.swift
  Projects/Rootrip/Rootrip/Views/Canvas/MapCanvasView.swift
  Projects/Rootrip/Rootrip/Views/Componants/MapCanvasToolBar.swift
  Projects/Rootrip/Rootrip/Views/Componants/MapCanvasToolPicker.swift
  Projects/Rootrip/Rootrip/Views/ProjectView.swift
  Projects/Rootrip/Rootrip/Views/Sidebar/SidebarToggleView.swift
  Projects/Rootrip/Rootrip/Views/ViewControllers/CanvasViewController.swift
Labels: BugFix
